version: 0.0
os: linux
files:
   - source: target/petclinic.war
     destination: /usr/share/tomcat7/webapps
permissions:
   - object: /usr/share/tomcat7/webapps
     pattern: "**"
     owner: tomcat
     group: tomcat
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/init.sh
      runas: root
    - location: scripts/load.sh
      runas: root
   AfterInstall:   
    - location: scripts/restart.sh
      runas: root
